# Generated by Django 6.1.1 on 2026-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('rating', models.FloatField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poster', models.URLField(blank=True)),
            ],
        ),
    ]
