# Generated by Django 6.1.1 on 2026-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='city',
            field=models.CharField(default='Jabalpur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='show_time',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.CharField(default='INOX', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
