# Generated by Django 6.1.1 on 2026-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_description_remove_movie_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
